# Generated by Django 3.2 on 2021-04-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharehouse_app', '0004_alter_property_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='date',
        ),
    ]
